<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260624172136 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE alert (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(50) NOT NULL, threshold_value DOUBLE PRECISION NOT NULL, is_active BOOLEAN NOT NULL, triggered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, watched_address_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_17FD46C1997D5CEC ON alert (watched_address_id)');
        $this->addSql('CREATE TABLE transaction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, txid VARCHAR(64) NOT NULL, amount DOUBLE PRECISION NOT NULL, confirmations INT NOT NULL, detected_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, watched_address_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_723705D1611BA490 ON transaction (txid)');
        $this->addSql('CREATE INDEX IDX_723705D1997D5CEC ON transaction (watched_address_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, password VARCHAR(255) NOT NULL, roles JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('CREATE TABLE watched_address (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, address VARCHAR(100) NOT NULL, label VARCHAR(100) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BEAF29907E3C61F9 ON watched_address (owner_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_address_per_owner ON watched_address (address, owner_id)');
        $this->addSql('ALTER TABLE alert ADD CONSTRAINT FK_17FD46C1997D5CEC FOREIGN KEY (watched_address_id) REFERENCES watched_address (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D1997D5CEC FOREIGN KEY (watched_address_id) REFERENCES watched_address (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE watched_address ADD CONSTRAINT FK_BEAF29907E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE alert DROP CONSTRAINT FK_17FD46C1997D5CEC');
        $this->addSql('ALTER TABLE transaction DROP CONSTRAINT FK_723705D1997D5CEC');
        $this->addSql('ALTER TABLE watched_address DROP CONSTRAINT FK_BEAF29907E3C61F9');
        $this->addSql('DROP TABLE alert');
        $this->addSql('DROP TABLE transaction');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE watched_address');
    }
}
